DEFAULT_FEATURES = {
    "Touch GUI": True,
    "Fix Bow & Arrow": True,
    "Fix Attacking": True,
    "Force Mob Spawning": False,
    "Fancy Graphics": True,
    "Disable Autojump By Default": True,
    "Display Nametags By Default": True,
    "Fix Sign Placement": True,
    "Show Block Outlines": True,
    "Expand Creative Inventory": True,
    "Remove Creative Mode Restrictions": True,
    "Peaceful Mode": False,
    "Animated Water": True,
    "Remove Invalid Item Background": True,
    'Disable "gui_blocks" Atlas': True,
    "Smooth Lighting": True,
    "3D Anaglyph": False,
    "Fix Camera Rendering": True,
    "Implement Chat": True,
    "Hide Chat Messages": False,
    "Implement Death Messages": True,
    "Implement Game-Mode Switching": True,
    "Allow Joining Survival Servers": True,
    "Miscellaneous Input Fixes": True,
    'Bind "Q" Key To Item Dropping': True,
    "Bind Common Toggleable Options To Function Keys": True,
    "Render Selected Item Text": True,
    "External Server Support": True,
    "Load Language Files": True,
    "Implement Sound Engine": True,
    "Close Current Screen On Death": True,
}

MINIMAL_FEATURES = {
    "Touch GUI": True,
    "Fix Bow & Arrow": True,
    "Fix Attacking": True,
    "Force Mob Spawning": False,
    "Fancy Graphics": False,
    "Disable Autojump By Default": True,
    "Display Nametags By Default": True,
    "Fix Sign Placement": True,
    "Show Block Outlines": True,
    "Expand Creative Inventory": True,
    "Remove Creative Mode Restrictions": True,
    "Peaceful Mode": False,
    "Animated Water": False,
    "Remove Invalid Item Background": True,
    'Disable "gui_blocks" Atlas': False,
    "Smooth Lighting": False,
    "3D Anaglyph": False,
    "Fix Camera Rendering": True,
    "Implement Chat": True,
    "Hide Chat Messages": False,
    "Implement Death Messages": True,
    "Implement Game-Mode Switching": True,
    "Allow Joining Survival Servers": True,
    "Miscellaneous Input Fixes": True,
    'Bind "Q" Key To Item Dropping': True,
    "Bind Common Toggleable Options To Function Keys": True,
    "Render Selected Item Text": True,
    "External Server Support": True,
    "Load Language Files": True,
    "Implement Sound Engine": True,
    "Close Current Screen On Death": True,
}

MODDED_MCPE_FEATURES = DEFAULT_FEATURES

CLASSIC_MCPI = dict()

MODDED_MCPI = {
    "Touch GUI": False,
    "Fix Bow & Arrow": True,
    "Fix Attacking": True,
    "Force Mob Spawning": False,
    "Fancy Graphics": True,
    "Disable Autojump By Default": True,
    "Display Nametags By Default": True,
    "Fix Sign Placement": True,
    "Show Block Outlines": True,
    "Expand Creative Inventory": True,
    "Remove Creative Mode Restrictions": True,
    "Peaceful Mode": False,
    "Animated Water": True,
    "Remove Invalid Item Background": True,
    'Disable "gui_blocks" Atlas': True,
    "Smooth Lighting": True,
    "3D Anaglyph": False,
    "Fix Camera Rendering": True,
    "Implement Chat": True,
    "Hide Chat Messages": False,
    "Implement Death Messages": True,
    "Implement Game-Mode Switching": True,
    "Allow Joining Survival Servers": True,
    "Miscellaneous Input Fixes": True,
    'Bind "Q" Key To Item Dropping': True,
    "Bind Common Toggleable Options To Function Keys": True,
    "Render Selected Item Text": True,
    "External Server Support": True,
    "Load Language Files": True,
    "Implement Sound Engine": True,
    "Close Current Screen On Death": True,
}

PROFILE_3D = {
    "Touch GUI": True,
    "Fix Bow & Arrow": True,
    "Fix Attacking": True,
    "Force Mob Spawning": False,
    "Fancy Graphics": True,
    "Disable Autojump By Default": True,
    "Display Nametags By Default": True,
    "Fix Sign Placement": True,
    "Show Block Outlines": True,
    "Expand Creative Inventory": True,
    "Remove Creative Mode Restrictions": True,
    "Peaceful Mode": False,
    "Animated Water": True,
    "Remove Invalid Item Background": True,
    'Disable "gui_blocks" Atlas': True,
    "Smooth Lighting": True,
    "3D Anaglyph": True,
    "Fix Camera Rendering": True,
    "Implement Chat": True,
    "Hide Chat Messages": False,
    "Implement Death Messages": True,
    "Implement Game-Mode Switching": True,
    "Allow Joining Survival Servers": True,
    "Miscellaneous Input Fixes": True,
    'Bind "Q" Key To Item Dropping': True,
    "Bind Common Toggleable Options To Function Keys": True,
    "Render Selected Item Text": True,
    "External Server Support": True,
    "Load Language Files": True,
    "Implement Sound Engine": True,
    "Close Current Screen On Death": True,
}
