SPLASHES = [
    "The moon is not a planet",
    "Pluto = Planet",
    "Ayy Yep!",
    "What's my purpose?",
    "MCPI_SPEEDHACK",
    "MCPIL-Revival",
    "Minescripters",
    "I use Planet BTW",
    "Snowball",
    "Robo",
    "If I could, I would. But I can't, so I shan't.",
    "SyntaxError: invalid syntax",
    "We Fixed The Rail!",
    "The World Of Notch!",
    "github.com/mcpiscript/Planet!",
    "Now with fly-hacks!",
    "Now with custom skins!",
    "Now with *fancy icons*!",
    "@Banana",
    "BANANA!",
    'To "Na" Or Not To "Na", that is the question!',
    "Not Minecraft Java!",
    "Oh yeah, that version...",
    "Segmentation fault (core dumped)",
    "It's the Segment's Fault!",
    "Who is StevePi?",
    "(Not) Made by Notch!",
    "Open-Source!",
    "RIP all MCPILs, 2020-2022",
    "StevePi = Leha confirmed?",
    "Watch out for StevePi!",
    "Didn't remove Herobrine!",
    "Check out PBPT Anarchy!",
    "你好中国",
    "한국 안녕하세요!",
    "日本ハロー！",
    "Привет Россия!",
    "Підтримай Україну!",
    "Supercalifragilisticexpialidocious!",
    "Now with multiplayer!",
    "ENGINEER GAMING",
    "Play Minecraft Pi Edition, watch Red-Exe-Engineer, get PIG!", 
]
