SPLASHES = [
    "The moon is not a planet",
    "Pluto = Planet",
    "Ayy Yep!",
    "What's my purpose?",
    "MCPI_SPEEDHACK", 
    "MCPIL-Revival", 
    "Minescripters", 
    "AmogOS is Debian with amogus wallpapers. Nothing sussy.", 
    "I use Planet btw.", 
    "Snowball", 
    "Robo", 
    "If I could, I would. But I can't, so I shan't.", 
    "I make a launcher! I break the launcher! Everyone hates it! Everyone hates it?", 
]
